php:
  build: .
  env_file: .env
  links:
    - mysql
  volumes:
    - .:/var/www/oberlo
nginx:
  image: nginx:1.9.10
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "8080:80"
mysql:
  build: ./.docker/mysql
  ports:
      - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}