<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;
use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function save(Message $message)
    {
        $this->_em->persist($message);
    }

    /**
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function flush()
    {
        $this->_em->flush();
    }
}
