services:
    messages.importer:
        class: AppBundle\Services\MessagesImportService
        arguments: ['@jms_serializer', "@=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:Message')"]
