list_messages:
  path:     /
  defaults: { _controller: AppBundle:Mailbox:list }

show_message:
  path:     /{messageId}
  defaults: { _controller: AppBundle:Mailbox:show }

read_message:
  path:     /{messageId}/read
  methods:  [ PATCH ]
  defaults: { _controller: AppBundle:Mailbox:read }

archive_message:
  path:     /{messageId}/archive
  methods:  [ PATCH ]
  defaults: { _controller: AppBundle:Mailbox:archive }
